### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by WyInnovate**
增加了一些环境变量的设置，但是请注意bucket相关的未测试！

### CODE REVIEW

**Comment by BerlinWong** [comment]
This README is really well written. In fact, it seems more appropriate not to use foreign key constraints. It may be that the functions reserved by the author when designing the program are not used in subsequent changes. For subsequent deployment, foreign key constraints can be ignored.

**Comment by WyInnovate** [comment]
有新版了的话那我把 PR 关了还是怎么🤔

**Comment by liujuntao123** [comment]
我关了哈，因为readme冲突了

**Comment by WyInnovate** [comment]
> 我关了哈，因为readme冲突了

你决定就好

**Pull request closed without merging**
